### ISSUE TITLE
XML_Toolkit: Pull Openings by Name

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/XML_Toolkit#290]
Pull openings not by openingType
`      <Opening openingType="NonSlidingDoor" id="opening-c6279">`

but by name

```
        <CADObjectId>Doors_ver01: SIM_INT_SLD [855631]</CADObjectId>
        <Name>Doors_ver01: SIM_INT_SLD</Name>
      </Opening>
```

![image](https://user-images.githubusercontent.com/26113670/59600245-98b81200-90f8-11e9-866d-dc9d13b7120b.png)

**Comment by FraserGreenroyd** [comment]
This is a non-issue - all openings are pulled regardless of their name or type. The type is assigned based on changing the string `openingType` to the `BH.oM.Environment.Elements.OpeningType` enum - see the code here:
https://github.com/BHoM/XML_Toolkit/blob/master/XML_Engine/Convert/Environment_oM/ElementType.cs#L154

If there is an issue with the opening types being pulled, remember that there is only a finite matching between openings that we have.

Please reply back here if there is a change to opening type assignment needed, otherwise, I shall presume this to be a non-issue for closure :smile:

**Comment by michaldengusiak** [comment]
this is not right I think you mix two items here, it is nothing to do with type...

we need to pull opening name and get unique opening name and not type...we assign type to opening but we need to keep name, so here is correct set up

```
        <CADObjectId>Doors_ver01: SIM_INT_SLD [858105]</CADObjectId>
        <Name>Doors_ver01: SIM_INT_SLD</Name>
      </Opening>
```

I noticed that I push gbMXL from pulled gbXML `CADObjectId` is missing and I think this is our problem...we need to make sure we can fill  `CADObjectId` 

```
        </PlanarGeometry>
        <CADObjectId />
        <Name>Doors_ver01: SIM_INT_SLD</Name>
      </Opening>
```

maybe we need to add revit style Element ID  `[000000]` to CADObjectID to get elements to be Unique, when we pull we ignore Element ID part and we have type data that we display
![image](https://user-images.githubusercontent.com/26113670/59613662-31f62100-9117-11e9-8d39-858aa312e7af.png)
