### ISSUE TITLE
Include Room ID and Room Name in XML Pull

### ISSUE THREAD

**Issue by KentonPhillips-BH** [BHoM/XML_Toolkit#367]
I want to pull an IES gbXML file into Grasshopper. At the space level we have Room Names, but at the panel level 'ConnectSpaces" shows the Room ID #.  Can we include the Room ID number in the Space object as well in order to reconstruct the model. 

![image](https://user-images.githubusercontent.com/57185336/67908864-7e387f80-fb53-11e9-994b-fb7661d6b124.png)

**Comment by FraserGreenroyd** [comment]
Hi @KentonPhillips-BH have you checked what the fragments of the space contain? Each space is given an `OriginContextFragment` which includes the `ElementID` of the space when it was pulled from the gbXML file.

If that doesn't solve the workflow you're trying to achieve then let me know and we can take a look at moving the space ID up onto the space object as its name rather than the current space name (i.e. flipping the association of ID and name on the space object when pulling).

@MajaLindroth FYI in case @KentonPhillips-BH confirms the flipping is the best course of action :smile:

**Comment by FraserGreenroyd** [comment]
Following discussion with @KentonPhillips-BH @BingWangUS and @MajaLindroth this issue has been deemed to be solved through the workflow of grabbing fragments described above. Closing as non-issue :smile:
