### ISSUE TITLE
Update readme and wiki to include KML

### ISSUE THREAD

**Issue by rolyhudson** [BHoM/XML_Toolkit#461]
#### What is missing/incorrect?
README.md needs to refer to KML version and documentation.

Wiki requires a restructure to reflect the now agnostic nature of the tool kit and restructure to provide separate documentation pages for schema (s) supported.

**Comment by rolyhudson** [comment]
@FraserGreenroyd before I make changes to the wiki pages wondering if on BHoM wiki edits do we use version control?

**Comment by FraserGreenroyd** [comment]
@rolyhudson no we generally don't but versioning comes in automatically with page histories typically.

**Comment by rolyhudson** [comment]
@FraserGreenroyd Thanks. I'm assigning named contributors to the wiki (except Sofia who I cannot find). Before I start  restructuring as suggested above I'd just like to check if any one has thoughts or suggestions or plans on the wiki.

**Comment by FraserGreenroyd** [comment]
No worries @rolyhudson . @mariatjader doesn't have access to her account anymore I don't think so I unassigned her. I also have no work/plans for the wiki so unassigned myself (to keep my to-do list fresh).

@vbeardow wrote the original wiki but does not have any plans for updates anytime soon and likewise I do not foresee that @michaldengusiak will have any changes. The gbXML part of XML_Toolkit wiki has been like that since December 2018, so I would say you're good to just go and make any necessary changes :smile:
